# Generated by Django 6.0 on 2026-02-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='plan_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.subscriptionplan'),
        ),
    ]
