# Generated by Django 6.0 on 2026-02-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_booking_product_booking_quantity_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('delivery', 'Delivery Boy')], default='user', max_length=10),
        ),
    ]
