# Generated by Django 6.0 on 2026-02-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_user_register_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='app1.user_register'),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivered_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('delivered', 'Delivered')], default='active', max_length=10),
        ),
    ]
