# Generated by Django 6.0 on 2026-02-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_booking_assigned_delivery_booking_delivered_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
