# Generated by Django 6.0 on 2026-02-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
